# Generated by Django 3.1.7 on 2021-02-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addevent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventname', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/')),
            ],
            options={
                'db_table': 'event2',
            },
        ),
    ]
