# Generated by Django 3.1.7 on 2021-02-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='addevent',
            name='islike',
            field=models.IntegerField(default=0),
        ),
    ]
