# Generated by Django 3.1.7 on 2021-02-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_addevent_islike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='addevent',
            table='addevent',
        ),
    ]
