# Generated by Django 3.1.7 on 2021-02-28 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0004_auto_20210228_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addevent',
            name='description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='addevent',
            name='eventname',
            field=models.CharField(max_length=500),
        ),
    ]
